[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"

# (Optional but recommended for React Router single-page apps)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
